# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install pytest
    - name: Test with pytest
      run: |
       pip install pytest pytest-cov
       pytest

    
    # - name: Run tests with coverage
    #     run: pytest --cov=your_module tests/ --cov-report=xml

      # - name: Generate coverage badge
      #   uses: cicirello/jacoco-badge-generator@v2.1.0
      #   with:
      #     coverage-files: coverage.xml
      #     badge-file: coverage-badge.svg

      # - name: Commit coverage badge
      #   run: |
      #     git config --global user.email "shaziamuckram@gmail.com"
      #     git config --global user.name "shaziamuckram"
      #     git add coverage-badge.svg
      #     git commit -m "Update coverage badge"
      #     git push
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}